
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import {Providers} from "./providers";
import { toast, ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";

// shared
import Navbar from "@/components/shared/Navbar"
import Footer from "@/components/shared/Footer" 
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JobFinds",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en" className="white">
      <body className={inter.className}>
        <Providers>

        <SessionProvider session={session}>
          <div className="mx-auto max-w-5xl  text-2xl gap-2 mb-10">
            <Navbar />
            {children}
            
            <Footer />
          </div>
          <ToastContainer />
        </SessionProvider>
        </Providers>
      
      </body>
    </html>
  );
}
